//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeManager.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FamilySymbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilySymbol()
        {
            this.RevitParameters = new HashSet<RevitParameter>();
        }
    
        public int Id { get; set; }

        
        public Nullable<int> FamilyId { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Scale { get; set; }
        public byte[] Image { get; set; }

        [ForeignKey("FamilyId")]
        public virtual Node Node { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<RevitParameter> RevitParameters { get; set; }
    }
}
