//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeManager.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RevitParameter
    {
        public int Id { get; set; }
        public Nullable<int> SymbolId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> StorageType { get; set; }
        [ForeignKey("SymbolId")]
        public virtual FamilySymbol FamilySymbol { get; set; }
    }
}
