//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeManager.Web.DBInfrastucture
{
    using System;
    //using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Microsoft.EntityFrameworkCore;
    //using System.Windows.Forms;


    public partial class NodeManagerDBEntities : DbContext
    {
        public NodeManagerDBEntities(DbContextOptions<NodeManagerDBEntities> options)
            : base(options)
        {
            //var f = new Form1();
            //f.Show();
            //Console.WriteLine("Enter password");
            //Database.Connection.ConnectionString = Database.Connection.ConnectionString.Replace("XXXXX", Console.ReadLine());
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<FamilySymbol> FamilySymbols { get; set; }
        public virtual DbSet<RevitParameter> RevitParameters { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<FSTags> FSTags { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Files> Files { get; set; }

    }
}
